name: Code coverage

on: [pull_request]

env:
  BUILD_FOLDER: backend/build

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            label: linux-64
            prefix: /usr/share/miniconda3/envs/neurobio
    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      
      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores

      - name: Setup environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: latest
          activate-environment: neurobio
          environment-file: backend/environment.yml
        
      - name: Install codecov
        run: |
          conda install -c conda-forge codecov

      - name: Print conda info
        run: | 
          conda info
          conda list
        
      - name: Install extra common dependencies
        run: | 
          git submodule update --init --recursive

      - name: Perform code coverage 
        run: |
          NEUROBIO_FOLDER=`pwd`
          CONDA_ENV_PATH=$CONDA/envs/neurobio
          mkdir -p $BUILD_FOLDER
          cd $BUILD_FOLDER
          cmake -DCMAKE_INSTALL_PREFIX=$CONDA_ENV_PATH -DCMAKE_BUILD_TYPE=Coverage -DBUILD_TESTS=ON ..
          cp -r test/models/ .
          make neurobio_coverage -j${{ steps.cpu-cores.outputs.count }}
          lcov --directory . --capture --output-file coverage.info
          lcov --remove coverage.info '/usr/*' --output-file coverage.info
          lcov --list coverage.info
          bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
          cd $NEUROBIO_FOLDER
