name: Run backend tests

on: [pull_request]

env:
  BUILD_FOLDER: backend/build

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            label: Linux
            prefix: /usr/share/miniconda3/envs/neurobio
          - os: macos-latest
            label: Macos
            prefix: /Users/runner/miniconda3/envs/neurobio
          - os: windows-latest
            label: Windows
            prefix: C:\Miniconda3\envs\neurobio
            
    name: Backend tests on ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      
      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores

      - name: Setup environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: latest
          activate-environment: neurobio
          environment-file: backend/environment.yml
  
      - name: Print conda info
        run: | 
          conda info
          conda list
        
      - name: Install extra common dependencies
        run: | 
          git submodule update --init --recursive

      - name: Build neurobiomech software UNIX
        run: |
          NEUROBIO_FOLDER=`pwd`
          CONDA_ENV_PATH=$CONDA/envs/neurobio
          mkdir -p $NEUROBIO_FOLDER/$BUILD_FOLDER
          cd $NEUROBIO_FOLDER/$BUILD_FOLDER
          cmake -DCMAKE_INSTALL_PREFIX=$CONDA_ENV_PATH -DCMAKE_BUILD_TYPE=Release -DSKIP_CI_FAILING_TESTS=ON -DBUILD_TESTS=ON ..
          make -j${{ steps.cpu-cores.outputs.count }}
          cd $NEUROBIO_FOLDER
        if: matrix.label != 'Windows'

      - name: Run tests UNIX
        run: |
          NEUROBIO_FOLDER=`pwd`
          cd $NEUROBIO_FOLDER/$BUILD_FOLDER/test
          ./neurobio_tests
          cd $NEUROBIO_FOLDER
        if: matrix.label != 'Windows'

      - name: Build neurobiomech software WINDOWS
        run: |
          NEUROBIO_FOLDER=`pwd`
          CONDA_ENV_PATH=$CONDA/envs/neurobio
          mkdir -p $NEUROBIO_FOLDER/$BUILD_FOLDER
          cd $NEUROBIO_FOLDER/$BUILD_FOLDER
          cmake -G"Visual Studio 17 2022" -Ax64 -DCMAKE_INSTALL_PREFIX=$CONDA_ENV_PATH -DCMAKE_BUILD_TYPE=Release -DSKIP_CI_FAILING_TESTS=ON -DBUILD_TESTS=ON ..
          cmake --build . --config Release -j${{ steps.cpu-cores.outputs.count }}
          cd $NEUROBIO_FOLDER
        if: matrix.label == 'Windows'

      - name: Run tests WINDOWS
        run: |
          NEUROBIO_FOLDER=`pwd`
          cd $NEUROBIO_FOLDER/$BUILD_FOLDER/test
          cp Release/neurobio_tests.exe .
          ./neurobio_tests.exe
          cd $NEUROBIO_FOLDER
        if: matrix.label == 'Windows'
