name: Run frontend tests

on: [pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            label: Linux
            prefix: /usr/share/miniconda3/envs/neurobio
          - os: macos-latest
            label: Macos
            prefix: /Users/runner/miniconda3/envs/neurobio
          - os: windows-latest
            label: Windows
            prefix: C:\Miniconda3\envs\neurobio

    name: Frontend tests on ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run install Flutter
        uses: subosito/flutter-action@v1

      - name: Run frontend tests
        run: |
          cd frontend
          flutter test
